'use client'
'./globals.scss'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css'
import Navbar from '@/components/navbar/Navbar'
const inter = Inter({ subsets: ['latin'] })
import '@/scss/common/app.scss';
import { LocalContextProvider } from '@/components/localContext/LocalContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <LocalContextProvider>
          {/* <Navbar /> */}
          {children}
        </LocalContextProvider>

      </body>
    </html>
  )
}
